---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootesssssssssssssssssssssssss
  labels:
    app: springbootesssssssssssssssssssssssss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootesssssssssssssssssssssssss
  template:
    metadata:
      labels:
        app: springbootesssssssssssssssssssssssss
    spec:
      containers:
        - name: springbootesssssssssssssssssssssssss
          image: docker.io/phengbunath/springbootesssssssssssssssssssssssss:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
